org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true

# Minecraft & Fabric
minecraft_version=1.21.1
yarn_mappings=1.21.1+build.9
loader_version=0.15.11
fabric_version=0.97.8+1.21.1

# Mod Properties
mod_version=1.0.0
maven_group=com.musor.visuals
archives_base_name=musorvisuals

# Dependencies
javax_annotation_version=3.0.2
